export default {
    CHECK_LOGIN_STATUS: 'check_login_status',
    LOGIN: 'login',
    ADD_INGREDIENT: 'add_ingredient',
    REMOVE_INGREDIENT: 'remove_ingredient',
    CLEAR_USER_INGREDIENT_INPUTS: 'clear_user_ingredient_inputs',
    USER_LOGOUT: 'user_logout',
    SEARCHED_RECIPE: 'searched_recipe',
    DETAILS_PAGE: 'details_page',
    ADD_TO_SHOPPINGLIST: 'add_to_shoppinglist',
    SIGN_UP: 'sign_up',
    REMOVE_FROM_SHOPPINGLIST: 'remove_from_shoppinglist',
    ADD_TO_FAVORITE: 'add_to_favorite',
    DELETE_FROM_FAVORITE: 'delete_from_favorite',
    GET_FAVORITE: 'get_favorites',
    GET_PAGE_NO: 'get_page_no',
    SET_PAGE_NO: 'set_page_no',
    CLEAR_SEARCHED_RECIPE: 'clear_searched_recipe',
    INVALID_SEARCH: 'invalid_search',
    LOGIN_DEFAULT: 'login_default'
}